<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>Learn Js</title>
    </head>
    <body>
        <h1>Hello home</h1>
    </body>
    <script>
        let add = (a, b) => {
            return new Promise((resolve, reject) => {
                setTimeout(() => {
                    if (typeof a != "number" || typeof b != "number") {
                        reject(new Error("Tham so phai la number"));
                    }
                    resolve(a + b);
                }, 2000);
            });
        };

        let a = add(4, "5").then(
            (result) => "ket qua:" + result,
            (err) => "err: " + err
        );
        // PromiseResult : underfine, vì nó ko đồng bộ, nên log chạy trước cả hàm add
        console.log(a);
        // PromiseResult: 9
        setTimeout(() => console.log(a), 2500);
        // nếu là reject thì PromiseResult là reject luôn.
        // vẫn trả về resolve dù có lỗi: nếu hàm then có xử lý lỗi
        //nhớ là giá trị trả về của promise nằm ở return của một trong hai function handle ở function then
    </script>
</html>
